// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNTMUxv_OlpT_m120wIh2o3FTe5Pymww',
    appId: '1:43817221860:web:caed31a726505214c536f1',
    messagingSenderId: '43817221860',
    projectId: 'brodbay-359a7',
    authDomain: 'brodbay-359a7.firebaseapp.com',
    storageBucket: 'brodbay-359a7.firebasestorage.app',
    measurementId: 'G-C35HH4W1FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuMcqLOZ4UgY00ktUF2Wkoe66iRf4FMdQ',
    appId: '1:43817221860:android:54e0d72c06f29560c536f1',
    messagingSenderId: '43817221860',
    projectId: 'brodbay-359a7',
    storageBucket: 'brodbay-359a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAwo917rSn_tMvNYIC7bMS4XwK5Bd39IY',
    appId: '1:43817221860:ios:1252f3a498d5382fc536f1',
    messagingSenderId: '43817221860',
    projectId: 'brodbay-359a7',
    storageBucket: 'brodbay-359a7.firebasestorage.app',
    iosClientId: '43817221860-h4vhlbajis8lklphtvrbhllb60ka85q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.brodbayProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAwo917rSn_tMvNYIC7bMS4XwK5Bd39IY',
    appId: '1:43817221860:ios:1252f3a498d5382fc536f1',
    messagingSenderId: '43817221860',
    projectId: 'brodbay-359a7',
    storageBucket: 'brodbay-359a7.firebasestorage.app',
    iosClientId: '43817221860-h4vhlbajis8lklphtvrbhllb60ka85q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.brodbayProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMNTMUxv_OlpT_m120wIh2o3FTe5Pymww',
    appId: '1:43817221860:web:c17c7419a8c4bfc0c536f1',
    messagingSenderId: '43817221860',
    projectId: 'brodbay-359a7',
    authDomain: 'brodbay-359a7.firebaseapp.com',
    storageBucket: 'brodbay-359a7.firebasestorage.app',
    measurementId: 'G-44S5M73BQ4',
  );
}
